// Company-operations arithmetic for the owner's dashboard and the support queue: UTC month
// buckets, subscription revenue net of estimated store fees, churn, the attention rules and
// support-case ageing and update rules. Pure functions: money in integer cents, `now` as input,
// no I/O.
export { MAX_REPORT_MONTHS, recentUtcMonths, utcMonthBounds, utcMonthKey } from './months.ts';
export {
  BASIS_POINTS_PER_UNIT,
  DEFAULT_STORE_FEE_RATE,
  DEFAULT_STRIPE_FEE_RATE,
  STRIPE_FEE_NOTE,
  basisPointsToRate,
  channelRevenue,
  defaultStoreFeeRate,
  rateToBasisPoints,
  storeFeeCents,
  sumRevenue,
  type ChannelRevenue,
  type ChannelRevenueInput,
  type RevenueTotals,
} from './revenue.ts';
export { churnBasisPoints, percentOfCap } from './subscriptions.ts';
export {
  ATTENTION_KINDS,
  DELETION_OVERDUE_AFTER_DAYS,
  DELETION_TARGET_DAYS,
  FAILED_JOBS_WINDOW_DAYS,
  FAILED_JOB_STATUSES,
  OPEN_CASE_STATUSES,
  OPEN_SAFETY_REPORT_STATUSES,
  ageHours,
  attentionItem,
  deletionOverdueBefore,
  failedJobsWindowStart,
  needsAttention,
  type AttentionItem,
  type AttentionKind,
} from './attention.ts';
export {
  CASE_AGE_BUCKETS,
  CASE_AGE_FILTERS,
  CASE_AGE_FILTER_KEYS,
  CASE_UPDATE_PROBLEMS,
  SUPPORT_CASE_KINDS,
  SUPPORT_CASE_PRIORITIES,
  SUPPORT_CASE_RESOLUTIONS,
  SUPPORT_CASE_STATUSES,
  SUPPORT_MESSAGE_MAX_LENGTH,
  SUPPORT_REFERENCE_MAX_LENGTH,
  SUPPORT_SUBJECT_MAX_LENGTH,
  applyCasePatch,
  caseAgeBucket,
  caseAgeHours,
  caseIsClosedOut,
  caseOpenedAtOrBefore,
  caseUpdateProblems,
  nextResolvedAt,
  parentCanReply,
  resolutionIsStoreRefund,
  resolutionRequiresReference,
  statusAfterParentReply,
  type CaseAgeBucket,
  type CaseAgeFilter,
  type CaseStateFacts,
  type CaseUpdatePatch,
  type CaseUpdateProblem,
  type SupportCaseKind,
  type SupportCasePriority,
  type SupportCaseResolution,
  type SupportCaseStatus,
} from './cases.ts';
