// Learning evidence, transparent skill status, practice prioritization, daily-set and Thursday
// review composition, retry limits and parent-override recomputation (spec P6, P7, P8, E4).
// Pure functions: no I/O, no clock (callers pass `now`), no randomness.
export {
  ATTEMPT_EVENT_ERROR_CODES,
  CORRECTNESS_VALUES,
  MAX_IDENTIFIER_LENGTH,
  effectiveCorrectness,
  isCorrectness,
  isIndependentAttempt,
  validateAttemptEvent,
  type AttemptEvent,
  type AttemptEventErrorCode,
  type Correctness,
  type ParentOverride,
} from './evidence.ts';
export {
  ACCURACY_EPSILON,
  DEFAULT_RECENCY_HALF_LIFE_DAYS,
  SKILL_STATUSES,
  SKILL_STATUS_RULES,
  ZONELESS_DAY_WINDOW_HOURS,
  recencyWeight,
  summarizeSkill,
  summarizeSkills,
  type SkillStatus,
  type SkillSummary,
  type SummaryConfig,
} from './summary.ts';
export {
  PRIORITY_POINTS,
  PRIORITY_REASONS,
  REPEATED_ERROR_RECENCY_DAYS,
  prioritizeSkills,
  type PrioritizeOptions,
  type PriorityReason,
  type RankedSkill,
} from './prioritize.ts';
export { ITEM_CATEGORIES, type CandidateItem, type ItemCategory } from './selection.ts';
export {
  DAILY_ITEM_SOURCES,
  DAILY_MIX_PERCENT,
  DAILY_SET_ERROR_CODES,
  DAILY_SET_MAX_COUNT,
  DAILY_SET_MIN_COUNT,
  DAILY_SLOTS,
  DEFAULT_DAILY_SET_COUNT,
  WEAK_SKILL_FIRST_PASS_CAP,
  composeDailySet,
  dailyMix,
  type DailyItemSource,
  type DailyMix,
  type DailySet,
  type DailySetErrorCode,
  type DailySetInput,
  type DailySetItem,
  type DailySetNote,
  type DailySlot,
} from './daily-set.ts';
export {
  DEFAULT_REVIEW_ITEMS_PER_SUBJECT,
  MAX_EVIDENCE_WINDOW_DAYS,
  MAX_REVIEW_ITEMS_PER_SUBJECT,
  MIN_REVIEW_ITEMS_PER_SUBJECT,
  MIN_TEST_SCOPE_QUESTIONS,
  REVIEW_BASES,
  REVIEW_ITEM_SOURCES,
  REVIEW_PARTS,
  THURSDAY_REVIEW_ERROR_CODES,
  composeThursdayReview,
  rankWeeklyWeaknesses,
  reviewSplit,
  validateEvidenceWindow,
  type EvidenceWindow,
  type ReviewBasis,
  type ReviewCandidateItem,
  type ReviewItem,
  type ReviewItemSource,
  type ReviewNote,
  type ReviewPart,
  type ReviewSection,
  type ThursdayReview,
  type ThursdayReviewErrorCode,
  type ThursdayReviewInput,
} from './thursday.ts';
export {
  DEFAULT_MAX_TARGET_ATTEMPTS,
  MAX_ALLOWED_TARGET_ATTEMPTS,
  RETRY_DECISIONS,
  countUnsuccessfulTargetAttempts,
  evaluateRetry,
  type RetryDecision,
  type RetryInput,
} from './retry.ts';
export {
  OVERRIDE_ERROR_CODES,
  recomputeAfterOverride,
  type OverrideAudit,
  type OverrideErrorCode,
  type OverrideRecomputation,
  type OverrideRequest,
} from './override.ts';
