// Curated, original science and social-studies multiple-choice items with grade tags (spec P7:
// "meaningful coverage of all six supported subjects"). Written for PencilLift; reviewed for a
// single defensible answer. Local/state curricula, labs, diagrams, maps and current events are not
// covered and are listed as unsupported in the coverage report.
import type { RandomSource } from '../shared/random.ts';
import { buildItem, choices, firstValid, prompt } from './build.ts';
import type { BankCategory, BankItem, BankSubject } from './types.ts';

export interface FactItem {
  readonly id: string;
  readonly subject: 'science' | 'social_studies';
  readonly skill: string;
  readonly gradeMin: number;
  readonly gradeMax: number;
  readonly stem: string;
  readonly correct: string;
  readonly distractors: readonly [string, string, string];
  readonly explanation: string;
}

const sci = (
  id: string,
  skill: 'life_science' | 'earth_space' | 'physical_science',
  grades: readonly [number, number],
  stem: string,
  correct: string,
  distractors: readonly [string, string, string],
  explanation: string,
): FactItem => ({
  id,
  subject: 'science',
  skill: `science.${skill}`,
  gradeMin: grades[0],
  gradeMax: grades[1],
  stem,
  correct,
  distractors,
  explanation,
});

const soc = (
  id: string,
  skill: 'geography' | 'civics' | 'history' | 'economics',
  grades: readonly [number, number],
  stem: string,
  correct: string,
  distractors: readonly [string, string, string],
  explanation: string,
): FactItem => ({
  id,
  subject: 'social_studies',
  skill: `social_studies.${skill}`,
  gradeMin: grades[0],
  gradeMax: grades[1],
  stem,
  correct,
  distractors,
  explanation,
});

export const SCIENCE_ITEMS: readonly FactItem[] = [
  sci(
    'plant_needs',
    'life_science',
    [0, 2],
    'What do green plants need to make their own food?',
    'Sunlight, water, and air',
    ['Only soil', 'Only rocks', 'Moonlight and sand'],
    'Green plants use sunlight, water, and carbon dioxide from the air to make food.',
  ),
  sci(
    'mammal',
    'life_science',
    [0, 2],
    'Which animal is a mammal?',
    'A dog',
    ['A frog', 'A robin', 'A goldfish'],
    'Mammals have hair or fur and feed their babies milk; dogs do, frogs, birds and fish do not.',
  ),
  sci(
    'puddle',
    'physical_science',
    [0, 2],
    'What happens to a puddle on a hot, sunny day?',
    'The water evaporates and the puddle gets smaller',
    ['The water freezes', 'The water turns into sand', 'The puddle gets deeper'],
    'Heat from the sun turns liquid water into water vapor (evaporation).',
  ),
  sci(
    'caterpillar',
    'life_science',
    [1, 3],
    'What does a caterpillar grow into?',
    'A butterfly or a moth',
    ['A spider', 'A frog', 'A snail'],
    'Caterpillars are the larva stage of butterflies and moths.',
  ),
  sci(
    'day_night',
    'earth_space',
    [1, 3],
    'What causes day and night on Earth?',
    'Earth spinning on its axis',
    ['The Moon blocking the Sun', 'Clouds covering the Sun', 'Earth moving closer to the Sun'],
    'As Earth spins, each place turns toward the Sun (day) and away from it (night).',
  ),
  sci(
    'solid',
    'physical_science',
    [1, 3],
    'Which of these is a solid?',
    'An ice cube',
    ['Steam from a kettle', 'Orange juice', 'The air inside a balloon'],
    'A solid keeps its own shape; ice is solid water.',
  ),
  sci(
    'heart',
    'life_science',
    [2, 4],
    'Which body part pumps blood through the body?',
    'The heart',
    ['The lungs', 'The stomach', 'The brain'],
    'The heart is a muscle that pumps blood.',
  ),
  sci(
    'condensation',
    'earth_space',
    [2, 4],
    'In the water cycle, what is it called when water vapor cools and turns into tiny drops that form clouds?',
    'Condensation',
    ['Evaporation', 'Erosion', 'Melting'],
    'Condensation is water vapor turning back into liquid drops.',
  ),
  sci(
    'roots',
    'life_science',
    [3, 5],
    'What is the main job of a plant’s roots?',
    'To take in water and hold the plant in place',
    ['To make seeds', 'To catch sunlight', 'To attract bees'],
    'Roots anchor the plant and absorb water and minerals from the soil.',
  ),
  sci(
    'magnet',
    'physical_science',
    [2, 4],
    'Which object will a magnet pull toward it?',
    'A steel paper clip',
    ['A wooden spoon', 'A plastic cup', 'A glass marble'],
    'Magnets attract objects that contain iron, such as steel.',
  ),
  sci(
    'mercury',
    'earth_space',
    [3, 5],
    'Which planet is closest to the Sun?',
    'Mercury',
    ['Venus', 'Earth', 'Mars'],
    'Mercury is the first planet from the Sun.',
  ),
  sci(
    'lungs',
    'life_science',
    [2, 5],
    'Which organs help you breathe in oxygen?',
    'The lungs',
    ['The kidneys', 'The bones', 'The ears'],
    'The lungs take in air and move oxygen into the blood.',
  ),
  sci(
    'sound',
    'physical_science',
    [3, 6],
    'What causes sound?',
    'Vibrations',
    ['Magnets', 'Shadows', 'Evaporation'],
    'Sound is made when something vibrates and the vibrations travel through air or other matter.',
  ),
  sci(
    'herbivore',
    'life_science',
    [4, 6],
    'In a food chain, what is an animal that eats only plants called?',
    'An herbivore',
    ['A carnivore', 'A decomposer', 'A predator'],
    'Herbivores eat plants; carnivores eat other animals.',
  ),
  sci(
    'igneous',
    'earth_space',
    [4, 6],
    'What type of rock forms when melted rock cools and hardens?',
    'Igneous rock',
    ['Sedimentary rock', 'Metamorphic rock', 'Limestone'],
    'Igneous rock forms from cooled magma or lava.',
  ),
  sci(
    'renewable',
    'earth_space',
    [4, 6],
    'Which energy resource is renewable?',
    'Sunlight',
    ['Coal', 'Oil', 'Natural gas'],
    'Sunlight keeps arriving; coal, oil and gas take millions of years to form.',
  ),
  sci(
    'newton',
    'physical_science',
    [5, 7],
    'Which unit is used to measure force?',
    'The newton',
    ['The meter', 'The liter', 'The degree'],
    'Force is measured in newtons.',
  ),
  sci(
    'kinetic',
    'physical_science',
    [5, 7],
    'What is the energy of a moving object called?',
    'Kinetic energy',
    ['Potential energy', 'Chemical energy', 'Nuclear energy'],
    'Kinetic energy is the energy of motion.',
  ),
  sci(
    'nucleus',
    'life_science',
    [5, 7],
    'Which part of a cell holds its genetic instructions (DNA)?',
    'The nucleus',
    ['The cell membrane', 'The cytoplasm', 'The vacuole'],
    'In plant and animal cells, DNA is stored in the nucleus.',
  ),
  sci(
    'seasons',
    'earth_space',
    [5, 8],
    'What causes the seasons on Earth?',
    'The tilt of Earth’s axis as Earth orbits the Sun',
    ['Earth’s distance from the Moon', 'Changes in the Sun’s size', 'Clouds blocking sunlight'],
    'Earth’s tilted axis changes how directly sunlight hits each hemisphere during the year.',
  ),
  sci(
    'atom',
    'physical_science',
    [6, 8],
    'What is the smallest unit of an element that still has the properties of that element?',
    'An atom',
    ['A cell', 'A grain of sand', 'A drop of water'],
    'An element is made of one kind of atom.',
  ),
  sci(
    'rust',
    'physical_science',
    [6, 8],
    'Which of these is a chemical change?',
    'Iron rusting',
    ['Ice melting', 'Paper being cut', 'Water boiling'],
    'Rusting makes a new substance (iron oxide); the others only change shape or state.',
  ),
  sci(
    'photosynthesis',
    'life_science',
    [6, 8],
    'What process do plants use to turn light energy into food?',
    'Photosynthesis',
    ['Respiration', 'Digestion', 'Pollination'],
    'Photosynthesis uses light, water and carbon dioxide to make sugar.',
  ),
  sci(
    'plates',
    'earth_space',
    [6, 8],
    'Where do most earthquakes happen?',
    'Along the edges of tectonic plates',
    ['Only in deserts', 'Only near the North Pole', 'Only where it rains a lot'],
    'Plates grinding, pulling apart or colliding at their edges cause most earthquakes.',
  ),
  sci(
    'population',
    'life_science',
    [7, 8],
    'What is a group of organisms of the same species living in one area called?',
    'A population',
    ['An ecosystem', 'A biome', 'An atmosphere'],
    'A population is one species in one area; an ecosystem includes many species and their surroundings.',
  ),
  sci(
    'newton_third',
    'physical_science',
    [7, 8],
    'When you push on a wall, how does the wall push on you?',
    'With an equal force in the opposite direction',
    [
      'With no force at all',
      'With a smaller force in the same direction',
      'With a larger force in the same direction',
    ],
    'Newton’s third law: forces come in equal and opposite pairs.',
  ),
];

export const SOCIAL_STUDIES_ITEMS: readonly FactItem[] = [
  soc(
    'map',
    'geography',
    [0, 2],
    'What is a map?',
    'A drawing that shows where places are',
    [
      'A list of words and their meanings',
      'A story about a family',
      'A picture of the weather tomorrow',
    ],
    'A map shows places and where they are.',
  ),
  soc(
    'water_body',
    'geography',
    [0, 2],
    'Which of these is a body of water?',
    'A lake',
    ['A mountain', 'A desert', 'A forest'],
    'Lakes, rivers and oceans are bodies of water.',
  ),
  soc(
    'rules',
    'civics',
    [0, 2],
    'Why do communities have rules and laws?',
    'To keep people safe and treat everyone fairly',
    ['To make people stay inside', 'To stop people from having fun', 'To tell people what to eat'],
    'Rules and laws help people live together safely and fairly.',
  ),
  soc(
    'directions',
    'geography',
    [1, 3],
    'What are the four main directions on a compass?',
    'North, south, east, and west',
    ['Up, down, left, and right', 'Hot, cold, wet, and dry', 'Front, back, top, and bottom'],
    'The cardinal directions are north, south, east and west.',
  ),
  soc(
    'needs',
    'economics',
    [1, 3],
    'Things people must have to live, like food and shelter, are called what?',
    'Needs',
    ['Wants', 'Toys', 'Hobbies'],
    'Needs are things required to live; wants are things that are nice to have.',
  ),
  soc(
    'timeline',
    'history',
    [1, 3],
    'What is a timeline used for?',
    'Showing events in the order they happened',
    ['Measuring how tall someone is', 'Finding places on a map', 'Counting money'],
    'A timeline puts events in time order.',
  ),
  soc(
    'consumer',
    'economics',
    [2, 4],
    'A person who buys goods or services is called what?',
    'A consumer',
    ['A producer', 'A mayor', 'A volunteer'],
    'Consumers buy and use goods and services; producers make them.',
  ),
  soc(
    'mayor',
    'civics',
    [2, 4],
    'In many U.S. cities, who is the leader of the city government?',
    'The mayor',
    ['The governor', 'The president', 'The principal'],
    'A mayor leads a city; a governor leads a state.',
  ),
  soc(
    'pacific',
    'geography',
    [2, 4],
    'Which is the largest ocean on Earth?',
    'The Pacific Ocean',
    ['The Atlantic Ocean', 'The Indian Ocean', 'The Arctic Ocean'],
    'The Pacific is the largest and deepest ocean.',
  ),
  soc(
    'kenya',
    'geography',
    [3, 5],
    'On which continent is the country of Kenya?',
    'Africa',
    ['Asia', 'Europe', 'South America'],
    'Kenya is in East Africa.',
  ),
  soc(
    'branches',
    'civics',
    [3, 5],
    'What are the three branches of the U.S. government?',
    'Legislative, executive, and judicial',
    ['City, county, and state', 'Army, navy, and air force', 'Schools, parks, and libraries'],
    'The Constitution divides power among the legislative, executive and judicial branches.',
  ),
  soc(
    'rivers',
    'history',
    [3, 5],
    'Why were many of the earliest cities built near rivers?',
    'Rivers gave people water for drinking and farming',
    [
      'Rivers kept away all visitors',
      'Rivers made the weather colder',
      'People could not build anywhere else',
    ],
    'Rivers provided water, fertile soil and transportation.',
  ),
  soc(
    'scarcity',
    'economics',
    [3, 5],
    'When there is not enough of something for everyone who wants it, what is it called?',
    'Scarcity',
    ['Surplus', 'Voting', 'Recycling'],
    'Scarcity means limited resources compared with what people want.',
  ),
  soc(
    'we_the_people',
    'civics',
    [4, 6],
    'Which document begins with the words “We the People”?',
    'The U.S. Constitution',
    ['The Declaration of Independence', 'The Gettysburg Address', 'The Emancipation Proclamation'],
    'The Preamble of the Constitution begins “We the People of the United States.”',
  ),
  soc(
    'declaration',
    'history',
    [4, 6],
    'In which year was the Declaration of Independence adopted?',
    '1776',
    ['1492', '1812', '1865'],
    'The Continental Congress adopted it on July 4, 1776.',
  ),
  soc(
    'latitude',
    'geography',
    [4, 6],
    'Lines of latitude measure distance in which directions?',
    'North or south of the equator',
    [
      'East or west of the prime meridian',
      'Above or below sea level',
      'Toward or away from the Sun',
    ],
    'Latitude is measured north and south of the equator.',
  ),
  soc(
    'senators',
    'civics',
    [4, 6],
    'How many U.S. senators does each state have?',
    'Two',
    ['One', 'Four', 'It depends on the state’s population'],
    'Every state has two senators; House seats depend on population.',
  ),
  soc(
    'egypt_pyramids',
    'history',
    [5, 7],
    'Which ancient civilization built pyramids along the Nile River?',
    'Ancient Egypt',
    ['Ancient Rome', 'Ancient Greece', 'Ancient China'],
    'The Egyptian pyramids stand near the Nile.',
  ),
  soc(
    'budget',
    'economics',
    [5, 7],
    'What is a budget?',
    'A plan for how to spend and save money',
    ['A kind of bank', 'A tax on food', 'A loan from a friend'],
    'A budget plans income, spending and saving.',
  ),
  soc(
    'judicial',
    'civics',
    [5, 8],
    'Which branch of the U.S. government interprets laws?',
    'The judicial branch',
    ['The legislative branch', 'The executive branch', 'The military'],
    'Courts, led by the Supreme Court, interpret laws.',
  ),
  soc(
    'printing_press',
    'history',
    [6, 8],
    'What was one major effect of the printing press developed by Johannes Gutenberg around 1450?',
    'Books and ideas spread faster and more widely',
    [
      'People stopped writing letters',
      'Paper became impossible to find',
      'Schools closed for many years',
    ],
    'Movable-type printing made books cheaper and faster to produce.',
  ),
  soc(
    'prime_meridian',
    'geography',
    [6, 8],
    'What is the prime meridian?',
    'The line of 0 degrees longitude',
    ['The equator', 'The border between two countries', 'The longest river in Europe'],
    'Longitude is measured east and west of the prime meridian.',
  ),
  soc(
    'bill_of_rights',
    'civics',
    [6, 8],
    'What is the main purpose of the Bill of Rights?',
    'To protect individual rights and freedoms',
    ['To set the price of goods', 'To choose the president', 'To draw state borders'],
    'The first ten amendments protect rights such as speech and religion.',
  ),
  soc(
    'silk_road',
    'history',
    [7, 8],
    'What was the Silk Road?',
    'A network of trade routes connecting Asia and Europe',
    ['A single paved highway in Rome', 'A river in South America', 'A castle wall in England'],
    'Traders exchanged goods and ideas along these routes for centuries.',
  ),
  soc(
    'demand',
    'economics',
    [7, 8],
    'If demand for a product rises while the supply stays the same, what usually happens to its price?',
    'It goes up',
    ['It goes down', 'It stays exactly the same', 'It drops to zero'],
    'More buyers competing for the same supply tends to raise the price.',
  ),
];

export function factItems(
  random: RandomSource,
  subject: Extract<BankSubject, 'science' | 'social_studies'>,
  grade: number,
  category: BankCategory,
  skill?: string,
): BankItem[] {
  const pool = subject === 'science' ? SCIENCE_ITEMS : SOCIAL_STUDIES_ITEMS;
  const target = category === 'accessible' ? Math.max(0, grade - 1) : grade;
  return pool
    .filter((f) => f.gradeMin <= target && target <= f.gradeMax)
    .filter((f) => skill === undefined || f.skill === skill)
    .flatMap((f) => {
      const item = firstValid(() => {
        const setup = choices(random, f.correct, f.distractors);
        return buildItem({
          templateKey: `${f.skill}.${f.id}.v1`,
          subject: f.subject,
          skill: f.skill,
          gradeMin: f.gradeMin,
          gradeMax: f.gradeMax,
          category,
          prompt: prompt(f.stem, 'choice', { choices: setup.choices }),
          answerSpec: setup.spec,
          explanation: f.explanation,
          distractor: setup.wrongLetter,
          params: { id: f.id },
        });
      });
      return item === null ? [] : [item];
    });
}
