// Deterministic homework checking and grading resolution (spec P5 checks/equivalents/verification,
// P6 verdict vocabulary). Safe parsing with exact rational arithmetic; never eval.
export {
  absRational,
  addRational,
  compareRational,
  divideRational,
  equalsRational,
  formatRational,
  isIntegerRational,
  multiplyRational,
  negateRational,
  powRational,
  rational,
  RATIONAL_ONE,
  RATIONAL_ZERO,
  rationalToDecimalString,
  roundRationalToPlaces,
  subtractRational,
  type Rational,
} from './rational.ts';
export {
  isSimplestForm,
  MAX_ANSWER_LENGTH,
  MAX_EXPONENT,
  MAX_NESTING_DEPTH,
  MAX_RESULT_DIGITS,
  MAX_TOKENS,
  normalizeMathText,
  parseMathAnswer,
  parseMathAnswerDetailed,
  PARSE_ERROR_CODES,
  type AnswerForm,
  type AnswerFormKind,
  type ParsedAnswer,
  type ParseErrorCode,
  type ParseOptions,
} from './parse.ts';
export {
  convertValue,
  DIMENSIONS,
  lookupUnit,
  parseQuantity,
  parseQuantityDetailed,
  QUANTITY_ERROR_CODES,
  UNIT_IDS,
  type DetailedQuantity,
  type Dimension,
  type Quantity,
  type QuantityErrorCode,
  type UnitDefinition,
  type UnitId,
} from './units.ts';
export {
  GRADING_REASONS,
  type CheckResult,
  type CheckVerdict,
  type GradeOutcome,
  type GradeVerdict,
  type GradingReason,
} from './verdicts.ts';
export {
  checkDivisionWithRemainder,
  checkExactText,
  checkMultipleChoice,
  checkNumericAnswer,
  checkSpelling,
  normalizeChoice,
  type DivisionExpected,
  type ExactTextExpected,
  type MultipleChoiceOptions,
  type NumericAnswerInput,
  type NumericExpected,
  type SpellingExpected,
  type Tolerance,
} from './checks.ts';
export {
  ANSWER_KINDS,
  CAPTURE_ISSUES,
  gradeObjectiveQuestion,
  gradeWorksheet,
  WORKSHEET_ERROR_CODES,
  type AnswerKind,
  type CaptureIssue,
  type ObjectiveQuestion,
  type WorksheetErrorCode,
  type WorksheetGrading,
  type WorksheetItem,
  type WorksheetResult,
} from './grade.ts';
export {
  DEFAULT_LOW_CONFIDENCE_THRESHOLD,
  resolveGrading,
  type DeterministicVerdict,
  type FinalVerdict,
  type GradingResolution,
  type ModelJudgment,
  type ModelVerdict,
  type ResolutionRoute,
  type ResolveGradingInput,
} from './resolve.ts';
