// P17 renewable one-month promotions: monthly campaign generation, code format, redemption
// validation/quote, target billing period and the durable redemption state machine.
export {
  CROCKFORD_ALPHABET,
  CROCKFORD_CHECK_ALPHABET,
  PROMO_CODE_DATA_LENGTH,
  PROMO_CODE_ERROR_CODES,
  PROMO_CODE_LENGTH,
  crockfordCheckSymbol,
  formatPromoCode,
  generatePromoCode,
  generatePromoCodes,
  normalizePromoCode,
  type GeneratePromoCodeOptions,
  type GeneratedPromoCode,
  type PromoCodeErrorCode,
} from './codes.ts';
export {
  CODE_MODES,
  MAX_INDIVIDUAL_CODES_PER_CAMPAIGN,
  PROMO_CHANNELS,
  SUBSCRIBER_CLASSES,
  TEMPLATE_ERROR_CODES,
  draftCampaignTemplate,
  explainMonthlyGeneration,
  generationKeyFor,
  planMonthlyGeneration,
  redemptionWindowUtc,
  validateTemplateForActivation,
  type CampaignTemplate,
  type CodeMode,
  type GenerationPlan,
  type GenerationPreview,
  type GenerationSkipReason,
  type MonthlyGenerationInput,
  type RedemptionWindow,
  type SubscriberClass,
  type TemplateDraftFields,
  type TemplateErrorCode,
} from './templates.ts';
export {
  CHANNEL_UNAVAILABLE_REASONS,
  MAPPING_STATUSES,
  channelAvailability,
  type ChannelAvailability,
  type ChannelMapping,
  type ChannelUnavailableReason,
  type MappingStatus,
} from './channels.ts';
export {
  EFFECTIVE_PRICE_ERROR_CODES,
  MAX_PERCENT_OFF,
  MIN_PERCENT_OFF,
  effectivePriceForPeriod,
  isValidPercentOff,
  previewDiscount,
  type ConfirmedPeriodRedemption,
  type DiscountPreview,
  type EffectivePeriodPrice,
  type EffectivePriceErrorCode,
} from './discount.ts';
export {
  DEFAULT_BILLING_CUTOFF_LEAD_MS,
  TARGET_PERIOD_ERROR_CODES,
  isFirstPeriodKey,
  isSameTargetPeriod,
  selectTargetPeriod,
  subscriberClassOf,
  targetPeriodKey,
  type PromoSubscriptionSnapshot,
  type PromoSubscriptionStatus,
  type TargetPeriod,
  type TargetPeriodErrorCode,
} from './target-period.ts';
export {
  LIVE_REDEMPTION_STATES,
  REDEMPTION_EVENTS,
  REDEMPTION_STATES,
  REDEMPTION_TRANSITION_ERROR_CODES,
  isDuplicateDelivery,
  isLiveState,
  transitionRedemption,
  type RedemptionEvent,
  type RedemptionState,
  type RedemptionTransitionErrorCode,
} from './redemption-state.ts';
export {
  REDEMPTION_ERROR_CODES,
  summarizeUsage,
  validateRedemption,
  type CampaignSnapshot,
  type CampaignStatus,
  type FamilyRedemptionRecord,
  type Principal,
  type PromoCodeRecord,
  type RedemptionErrorCode,
  type RedemptionQuote,
  type RedemptionValidationInput,
} from './redemption.ts';
export {
  confirmationSummary,
  type ConfirmationSummary,
  type DiscountedPeriodView,
} from './confirmation.ts';
