#!/usr/bin/env python3
"""Render docs/Requirement_Coverage.md from the spec's acceptance register and docs/coverage_status.json.

Rows come from the master prompt itself so the matrix cannot silently drop a requirement (AC_DEPLOY_08).
Every ID without an entry in coverage_status.json is reported as `not_tested`.
"""
import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "PencilLift_Claude_Code_Master_Prompt.md"
STATUS = ROOT / "docs" / "coverage_status.json"
OUT = ROOT / "docs" / "Requirement_Coverage.md"

ALLOWED = [
    "not_tested", "in_progress", "verified_by_inspection", "unit_tested", "db_tested", "integration_tested",
    "mock_only", "blocked_external", "sandbox_verified", "production_verified",
]

def main() -> int:
    rows = []
    for line in SPEC.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^\|\s*(AC_[A-Z]+_\d+)\s*\|\s*(.+?)\s*\|\s*$", line)
        if m:
            rows.append((m.group(1), m.group(2)))
    ids = [r[0] for r in rows]
    dupes = [i for i, n in Counter(ids).items() if n > 1]
    if dupes:
        print(f"Duplicate acceptance IDs in spec: {dupes}", file=sys.stderr)
        return 1
    status = json.loads(STATUS.read_text(encoding="utf-8")) if STATUS.exists() else {}
    unknown = sorted(set(status) - set(ids))
    if unknown:
        print(f"coverage_status.json has IDs not in the spec: {unknown}", file=sys.stderr)
        return 1
    counts = Counter()
    lines = []
    for ac, text in rows:
        entry = status.get(ac, {})
        st = entry.get("status", "not_tested")
        if st not in ALLOWED:
            print(f"{ac}: invalid status {st}", file=sys.stderr)
            return 1
        counts[st] += 1
        short = text if len(text) <= 140 else text[:137] + "..."
        cells = [
            ac,
            short,
            st,
            entry.get("implementation", "—"),
            entry.get("check", "—"),
            entry.get("evidence", "—"),
            entry.get("gap", "—") or "—",
        ]
        lines.append("| " + " | ".join(" ".join(c.split()).replace("|", "\\|") for c in cells) + " |")
    header = [
        "# Requirement coverage (spec E1, AC_DEPLOY_08)",
        "",
        "Generated by `python3 scripts/render-coverage.py` from the spec's acceptance register and",
        "`docs/coverage_status.json`. Do not edit by hand. Statuses: " + ", ".join(f"`{s}`" for s in ALLOWED) + ".",
        "`unit_tested`/`db_tested` mean automated checks pass locally against the code in this repository; they are",
        "not sandbox, native-device or production evidence.",
        "",
        f"**{len(rows)} acceptance checks.** " + ", ".join(f"{s}: {counts[s]}" for s in ALLOWED if counts[s]),
        "",
        "Gap names the weakest clause that keeps a row from a stronger status (what is missing and why).",
        "",
        "| ID | Required outcome | Status | Implementation | Check | Evidence | Gap |",
        "|---|---|---|---|---|---|---|",
    ]
    OUT.write_text("\n".join(header + lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(rows)} checks; " + ", ".join(f"{k}={v}" for k, v in counts.items()))
    return 0

if __name__ == "__main__":
    sys.exit(main())
