// Usage allowances, in-flight reservations, AI cost metering and spend ceilings
// (spec P11 quotas paragraph, P12 usage/cost, F3, F4 controls).
export {
  COST_ERROR_CODES,
  computeOperationCostMicros,
  DEFAULT_RATE_TABLE_2026_09_18,
  estimateUpperBoundCostMicros,
  type CostAssumption,
  type CostErrorCode,
  type ModelRate,
  type ModelRateTable,
  type OperationCost,
  type OperationUsage,
  type UpperBoundEstimateInput,
} from './rates.ts';
export {
  ALLOWANCE_ERROR_CODES,
  allowanceUsage,
  commit,
  DEFAULT_ALLOWANCE_CONFIG,
  EMPTY_ALLOWANCE_STATE,
  release,
  reserve,
  type AllowanceChange,
  type AllowanceConfig,
  type AllowanceErrorCode,
  type AllowanceReservation,
  type AllowanceState,
  type AllowanceUsageQuery,
  type AllowanceUsageReport,
  type QuotaScope,
  type ReleaseReason,
  type ReservationStatus,
  type ReserveRequest,
} from './allowance.ts';
export {
  DEFAULT_ALERT_THRESHOLDS_PERCENT,
  EMPTY_SPEND_LEDGER,
  evaluateSpend,
  reserveSpend,
  settleSpend,
  SPEND_ERROR_CODES,
  spendTotals,
  type SpendCheckInput,
  type SpendErrorCode,
  type SpendEvaluation,
  type SpendLedger,
  type SpendOutcome,
  type SpendReservation,
  type SpendReserveOutcome,
  type SpendReserveRequest,
  type SpendSettleChange,
  type SpendSettlement,
  type SpendTotals,
} from './spend.ts';
export {
  AI_STAGES,
  canAttempt,
  defineStageLimits,
  isAiStage,
  type AiStage,
  type AttemptDecision,
  type AttemptUsage,
  type StageDenyReason,
  type StageLimits,
  type StageLimitsTable,
} from './stages.ts';
export {
  exhaustionOutcome,
  PRESERVED_ON_EXHAUSTION,
  type ExhaustionKind,
  type ExhaustionOutcome,
  type ParentChoice,
  type PreservedItem,
} from './exhaustion.ts';
